# Generated by Django 5.2 on 2025-09-30 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Rollno', models.CharField(max_length=10)),
                ('cls', models.CharField(choices=[('BCA', 'BCA'), ('BBA', 'BBA'), ('BCOM', 'BCOM'), ('MCA', 'MCA')], max_length=5)),
                ('current_year', models.CharField(choices=[('1YEAR', '1YEAR'), ('2YEAR', '2YEAR'), ('3YEAR', 'YEAR')], max_length=5, null=True)),
                ('email', models.EmailField(default='chandu@gmail.com', max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
