# Generated by Django 5.2 on 2025-09-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Rollno', models.CharField(max_length=10)),
                ('cls', models.CharField(choices=[('BCA', 'BCA'), ('BBA', 'BBA'), ('BCOM', 'BCOM'), ('MCA', 'MCA')], max_length=5)),
                ('current_year', models.CharField(choices=[('1YEAR', '1YEAR'), ('2YEAR', '2YEAR'), ('3YEAR', 'YEAR')], max_length=5, null=True)),
            ],
        ),
    ]
