# Generated by Django 5.2 on 2025-10-02 07:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(choices=[('BCA', 'BCA'), ('BCOM', 'BCOM'), ('BBA', 'BBA')], max_length=10)),
                ('current_year', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year')])),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Rollno', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField(default=0)),
                ('Course_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studentinfo.course')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studentinfo.student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studentinfo.student'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment1', models.BooleanField(default=False)),
                ('assignment2', models.BooleanField(default=False)),
                ('due_date1', models.DateField(default=django.utils.timezone.now)),
                ('due_date2', models.DateField(default=django.utils.timezone.now)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='ass1/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='ass2/')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studentinfo.student')),
            ],
        ),
    ]
